import type { KeyInfoType } from './types'

export const letters: Record<string, KeyInfoType> = {
  a: {
    title: 'lowercase',
    action: 'command',
    hasBorder: true,
    vimHelp: 'insert.txt.html#a',
    plugins:
      'tpope/vim-speeddating | Increment dates, times, and more with CTRL-a/CTRL-x.',
    text: 'Append — enter insert mode <b>after</b> the cursor. Also used as the "around" selector in text objects (<code>a{selector}</code>). <code>Ctrl-a</code> increments the number under the cursor.',
    examples: ['a', 'ea (append after word)', 'Ctrl-a (increment number)'],
    secondaryText: 'append',
    numberIndicator: ['1', '4'],
  },
  A: {
    title: 'UPPERCASE',
    action: 'command',
    hasBorder: true,
    vimHelp: 'insert.txt.html#A',
    text: 'Append at end of line — move to the end of the current line and enter insert mode.',
    examples: ['A', 'A;<Esc> (add semicolon to end)'],
    secondaryText: 'append eol',
  },
  b: {
    title: 'lowercase',
    action: 'motion',
    vimHelp: 'motion.txt.html#b',
    plugins:
      'bkad/CamelCaseMotion | Adds <leader>b / <leader>w / <leader>e to move by subword within CamelCase and snake_case identifiers.',
    text: 'Move backward [count] words. Stops at the <b>start</b> of each word. Punctuation counts as word boundaries.',
    examples: ['b', '3b', 'db (delete to prev word start)', 'cb'],
    secondaryText: 'prev word',
  },
  B: {
    title: 'UPPERCASE',
    action: 'motion',
    vimHelp: 'motion.txt.html#B',
    text: 'Move backward [count] WORDS. Like <code>b</code> but only whitespace counts as a boundary — punctuation is ignored.',
    examples: ['B', '3B', 'dB'],
    secondaryText: 'prev WORD',
  },
  c: {
    title: 'lowercase',
    action: 'operator',
    vimHelp: 'change.txt.html#c',
    plugins:
      'tpope/vim-surround | cs{old}{new} changes surrounding chars. e.g. cs"\' changes " to \'. || tpope/vim-commentary | gc{motion} or gcc to comment/uncomment lines.',
    text: 'Change operator — delete the text covered by the motion and enter insert mode. Double <code>cc</code> changes the whole line.',
    examples: [
      'cw (change word)',
      'cc (change line)',
      'ci" (change inside quotes)',
      'c$ or C (change to end)',
    ],
    secondaryText: 'change',
    numberIndicator: ['1', '3'],
  },
  C: {
    title: 'UPPERCASE',
    action: 'command',
    hasBorder: true,
    vimHelp: 'change.txt.html#C',
    text: 'Delete from cursor to end of line and enter insert mode. Shorthand for <code>c$</code>.',
    examples: ['C', '"aC (change into register a)'],
    secondaryText: 'change to end of line',
    shortText: 'chg eol',
  },
  d: {
    title: 'lowercase',
    action: 'operator',
    vimHelp: 'change.txt.html#d',
    plugins:
      'tpope/vim-surround | ds{char} deletes surrounding character. e.g. ds" removes surrounding quotes, ds) removes parens.',
    text: 'Delete operator — removes the text covered by the motion into a register (default: unnamed <code>"</code>). Double <code>dd</code> deletes the whole line.',
    examples: [
      'dd (delete line)',
      'dw (delete word)',
      'd$ or D (delete to end)',
      'diw (delete inner word)',
      '3dd (delete 3 lines)',
    ],
    secondaryText: 'delete',
    numberIndicator: ['1', '3'],
  },
  D: {
    title: 'UPPERCASE',
    action: 'command',
    vimHelp: 'change.txt.html#D',
    text: 'Delete from cursor to end of line. Shorthand for <code>d$</code>.',
    examples: ['D', '"aD (delete into register a)'],
    secondaryText: 'delete to end of line',
    shortText: 'del eol',
  },
  e: {
    title: 'lowercase',
    action: 'motion',
    vimHelp: 'motion.txt.html#e',
    plugins:
      'bkad/CamelCaseMotion | Adds <leader>e to move to the end of a subword within CamelCase and snake_case identifiers.',
    text: 'Move forward to the <b>end</b> of the current (or next) word [count] times. Does not stop on empty lines.',
    examples: [
      'e',
      '3e',
      'de (delete to end of word)',
      'ce (change to end of word)',
    ],
    secondaryText: 'end word',
  },
  E: {
    title: 'UPPERCASE',
    action: 'motion',
    vimHelp: 'motion.txt.html#E',
    text: 'Move forward to the <b>end</b> of the current WORD [count] times. Like <code>e</code> but only whitespace counts as a boundary.',
    examples: ['E', 'dE', 'cE'],
    secondaryText: 'end WORD',
  },
  f: {
    title: 'lowercase',
    action: 'motion',
    hasDot: true,
    vimHelp: 'motion.txt.html#f',
    plugins:
      'dahu/vim-fanfingtastic | Extends f, F, t, T to search across multiple lines instead of stopping at the end of the current line.',
    text: "Find — move cursor to the [count]'th occurrence of a character <b>to the right</b> on the current line. Cursor lands <b>on</b> the character. Repeat with <code>;</code>, reverse with <code>,</code>.",
    examples: [
      'fa (jump to next "a")',
      'df, (delete to next comma)',
      '3f( (3rd next paren)',
      'ct; (change till semicolon)',
    ],
    secondaryText: 'find char',
  },
  F: {
    title: 'UPPERCASE',
    action: 'motion',
    hasDot: true,
    vimHelp: 'motion.txt.html#F',
    plugins:
      'dahu/vim-fanfingtastic | Extends f, F, t, T to search across multiple lines.',
    text: "Find backward — move cursor to the [count]'th occurrence of a character <b>to the left</b> on the current line. Repeat with <code>;</code>, reverse with <code>,</code>.",
    examples: ['F(', 'dF,', 'F; (find prev semicolon)'],
    secondaryText: 'back find char',
    shortText: 'back find',
  },
  g: {
    title: 'lowercase',
    action: 'extra',
    hasDot: true,
    vimHelp: 'index.txt.html#g',
    plugins:
      'tpope/vim-commentary | gcc comments line, gc{motion} comments range, gcu uncomments. || tpope/vim-characterize | ga shows Unicode name, codepoint, HTML entity & digraph for char under cursor. || tommcdo/vim-lion | gl{motion}{char} left-aligns to char, gL right-aligns.',
    text: 'Prefix for many powerful commands. Toggle the <b>g</b> overlay in the header to see all <code>g+key</code> mappings. Run <code>:help g</code> in Vim for the full list.',
    examples: [
      'gg (top of file)',
      'gd (goto definition)',
      'gf (open file under cursor)',
      'g~ (toggle case)',
      'gv (reselect last visual)',
    ],
    secondaryText: 'extra cmds',
    numberIndicator: '6',
  },
  G: {
    title: 'UPPERCASE',
    action: 'motion',
    hasDot: true,
    vimHelp: 'motion.txt.html#G',
    text: 'Go to line [count]. Without a count, jumps to the <b>last line</b>. With a count, jumps to that line number. Lands on the first non-blank character.',
    examples: [
      'G (last line)',
      '1G or gg (first line)',
      '50G (line 50)',
      'dG (delete to end of file)',
    ],
    secondaryText: 'eof/goto line',
    shortText: 'goto ln',
  },
  h: {
    title: 'lowercase',
    action: 'motion',
    vimHelp: 'motion.txt.html#h',
    text: 'Move left [count] columns. Will not wrap to the previous line.',
    examples: ['h', '5h', 'dh (delete char to left)'],
    secondaryText: '←',
  },
  H: {
    title: 'UPPERCASE',
    action: 'motion',
    vimHelp: 'motion.txt.html#H',
    text: 'Move to the top (High) of the visible window, on the first non-blank character. Use <code>zt</code> to scroll the window instead.',
    examples: ['H', 'dH (delete to top of screen)'],
    secondaryText: 'screen top',
  },
  i: {
    title: 'lowercase',
    action: 'command',
    hasBorder: true,
    vimHelp: 'insert.txt.html#i',
    text: 'Insert — enter insert mode <b>before</b> the cursor. Also used as the "inner" selector in text objects (<code>i{selector}</code>).',
    examples: ['i', '5i-<Esc> (insert "-----")', 'I (insert at line start)'],
    secondaryText: 'insert mode',
  },
  I: {
    title: 'UPPERCASE',
    action: 'command',
    hasBorder: true,
    vimHelp: 'insert.txt.html#I',
    text: 'Insert at the beginning of the line — move to the first non-blank character and enter insert mode.',
    examples: ['I', 'I// <Esc> (comment out a line)'],
    secondaryText: 'insert at bol',
    shortText: 'insert bol',
  },
  j: {
    title: 'lowercase',
    action: 'motion',
    vimHelp: 'motion.txt.html#j',
    text: 'Move down [count] lines, staying in the same column where possible.',
    examples: [
      'j',
      '5j',
      'dj (delete current + next line)',
      'gj (move down by display line)',
    ],
    secondaryText: '↓',
  },
  J: {
    title: 'UPPERCASE',
    action: 'command',
    vimHelp: 'change.txt.html#J',
    text: 'Join — append the next line to the end of the current line, replacing the newline with a single space. Use <code>gJ</code> to join without adding a space.',
    examples: ['J', '3J (join 3 lines)', 'gJ (join without space)'],
    secondaryText: 'join lines',
  },
  k: {
    title: 'lowercase',
    action: 'motion',
    vimHelp: 'motion.txt.html#k',
    text: 'Move up [count] lines, staying in the same column where possible.',
    examples: [
      'k',
      '5k',
      'dk (delete current + prev line)',
      'gk (move up by display line)',
    ],
    secondaryText: '↑',
  },
  K: {
    title: 'UPPERCASE',
    action: 'command',
    vimHelp: 'various.txt.html#K',
    text: 'Look up the word under the cursor using <code>keywordprg</code> (default: man page). Commonly remapped in LSP configs to show hover documentation: <code>nnoremap K &lt;cmd&gt;lua vim.lsp.buf.hover()&lt;cr&gt;</code>.',
    examples: [
      'K (lookup word)',
      'K (LSP hover if configured)',
      ':set keywordprg=:help (use vim help)',
    ],
    secondaryText: 'help / hover',
  },
  l: {
    title: 'lowercase',
    action: 'motion',
    vimHelp: 'motion.txt.html#l',
    text: 'Move right [count] columns. Will not wrap to the next line.',
    examples: ['l', '5l', 'dl (delete char under cursor, like x)'],
    secondaryText: '→',
  },
  L: {
    title: 'UPPERCASE',
    action: 'motion',
    vimHelp: 'motion.txt.html#L',
    text: 'Move to the bottom (Low) of the visible window, on the first non-blank character. Use <code>zb</code> to scroll the window instead.',
    examples: ['L', 'dL (delete to bottom of screen)'],
    secondaryText: 'screen bottom',
    shortText: 'screen bot',
  },
  m: {
    title: 'lowercase',
    action: 'command',
    hasDot: true,
    vimHelp: 'motion.txt.html#m',
    text: "Set a mark at the cursor position. Lowercase marks (<code>a-z</code>) are local to the file. Uppercase marks (<code>A-Z</code>) are global across files. Jump back with <code>'</code> (line) or <code>`</code> (exact position).",
    examples: [
      'ma (set mark a)',
      "'a (jump to line of mark a)",
      '`a (jump to exact position)',
      'dm (delete to mark)',
    ],
    secondaryText: 'set mark',
  },
  M: {
    title: 'UPPERCASE',
    action: 'motion',
    vimHelp: 'motion.txt.html#M',
    text: 'Move to the middle (Middle) of the visible window, on the first non-blank character.',
    examples: ['M'],
    secondaryText: 'screen mid',
    shortText: 'screen mid',
  },
  n: {
    title: 'lowercase',
    action: 'motion',
    vimHelp: 'pattern.txt.html#n',
    text: 'Repeat the last <code>/</code> or <code>?</code> search, moving to the <b>next</b> match in the same direction.',
    examples: [
      'n (next match)',
      '5n (5th next match)',
      ':noh (clear highlights)',
    ],
    secondaryText: 'next match',
  },
  N: {
    title: 'UPPERCASE',
    action: 'motion',
    vimHelp: 'pattern.txt.html#N',
    text: 'Repeat the last search in the <b>opposite</b> direction.',
    examples: ['N (previous match)', '3N'],
    secondaryText: 'prev match',
  },
  o: {
    title: 'lowercase',
    action: 'command',
    hasBorder: true,
    vimHelp: 'insert.txt.html#o',
    text: 'Open a new line <b>below</b> the current line and enter insert mode.',
    examples: ['o', '3o---<Esc> (insert 3 lines of "---")'],
    secondaryText: 'open below',
  },
  O: {
    title: 'UPPERCASE',
    action: 'command',
    hasBorder: true,
    vimHelp: 'insert.txt.html#O',
    text: 'Open a new line <b>above</b> the current line and enter insert mode.',
    examples: ['O'],
    secondaryText: 'open above',
  },
  p: {
    title: 'lowercase',
    action: 'command',
    vimHelp: 'change.txt.html#p',
    plugins:
      'tpope/vim-unimpaired | ]p pastes after with auto-indent matching the current line. [p pastes before with indent.',
    text: 'Paste the contents of the unnamed register <b>after</b> the cursor. For linewise yanks, pastes below the current line.',
    examples: [
      'p',
      '"ap (paste from register a)',
      '3p (paste 3 times)',
      'P (paste before cursor)',
      ']p (paste with indent)',
    ],
    secondaryText: 'paste after',
    numberIndicator: '1',
  },
  P: {
    title: 'UPPERCASE',
    action: 'command',
    vimHelp: 'change.txt.html#P',
    plugins:
      'tpope/vim-unimpaired | [p pastes before with auto-indent. ]p pastes after with indent.',
    text: 'Paste the contents of the unnamed register <b>before</b> the cursor. For linewise yanks, pastes above the current line.',
    examples: [
      'P',
      '"aP (paste from register a before)',
      '[p (paste above with indent)',
    ],
    secondaryText: 'paste before',
    shortText: 'paste ←',
  },
  q: {
    title: 'lowercase',
    action: 'command',
    hasDot: true,
    vimHelp: 'repeat.txt.html#q',
    text: 'Record a macro into register <code>{a-z}</code>. Press <code>q</code> again to stop recording. Replay with <code>@{reg}</code>. Use <code>@@</code> to repeat the last macro.',
    examples: [
      'qq (record to q)',
      'q (stop recording)',
      '@q (replay macro q)',
      '@@',
      '5@q (replay 5 times)',
    ],
    secondaryText: 'record macro',
    shortText: 'record',
    numberIndicator: '1',
  },
  Q: {
    title: 'UPPERCASE',
    action: 'command',
    vimHelp: 'intro.txt.html#Q',
    text: 'Enter Ex mode — each line is executed as a command-line command. Type <code>visual</code> to return to Normal mode. Note: <code>gq{motion}</code> (format/wrap text) and <code>@q</code> (replay macro) are more commonly used in practice. Many configs remap Q to <code>@q</code>.',
    examples: [
      'Q (enter Ex mode)',
      ':visual or :vi (exit Ex mode)',
      'gqip (wrap paragraph)',
      'gq$ (wrap to end)',
    ],
    secondaryText: 'ex mode',
  },
  r: {
    title: 'lowercase',
    action: 'command',
    hasDot: true,
    vimHelp: 'change.txt.html#r',
    plugins:
      'tpope/vim-abolish | cr{suffix} coerces word case under cursor: crs (snake_case), crc (camelCase), crm (MixedCase), cru (UPPER_CASE), cr- (dash-case).',
    text: 'Replace — replace the character under cursor with the next typed character, then stay in Normal mode.',
    examples: [
      'ra (replace with "a")',
      '3rx (replace 3 chars with "x")',
      'r<Enter> (replace with newline)',
    ],
    secondaryText: 'replace char',
    shortText: 'repl chr',
    numberIndicator: '3',
  },
  R: {
    title: 'UPPERCASE',
    action: 'command',
    hasBorder: true,
    vimHelp: 'change.txt.html#R',
    text: 'Enter Replace mode — each keystroke overwrites the character under cursor. Backspace restores the original character.',
    examples: ['R (enter replace mode)', '<Esc> (exit replace mode)'],
    secondaryText: 'replace mode',
    shortText: 'repl mode',
  },
  s: {
    title: 'lowercase',
    action: 'command',
    hasBorder: true,
    vimHelp: 'change.txt.html#s',
    plugins:
      'christoomey/vim-sort-motion | gs{motion} sorts lines. gsip sorts paragraph, gsi( sorts within parens.',
    text: 'Substitute — delete [count] characters under cursor and enter insert mode. Shorthand for <code>cl</code>.',
    examples: ['s', '3s (substitute 3 chars)', 'S (substitute whole line)'],
    secondaryText: 'substitute char',
    shortText: 'subst',
  },
  S: {
    title: 'UPPERCASE',
    action: 'command',
    hasBorder: true,
    vimHelp: 'change.txt.html#S',
    plugins:
      'tpope/vim-surround | S{char} in Visual mode wraps the selection in the given character. e.g. select text then S" to wrap in quotes.',
    text: 'Substitute line — delete [count] lines and enter insert mode. Shorthand for <code>cc</code>.',
    examples: ['S', '3S (substitute 3 lines)'],
    secondaryText: 'substitute line',
    shortText: 'subst ln',
  },
  t: {
    title: 'lowercase',
    action: 'motion',
    vimHelp: 'motion.txt.html#t',
    plugins:
      'dahu/vim-fanfingtastic | Extends f, F, t, T to search across multiple lines.',
    text: "Till — move cursor to just <b>before</b> the [count]'th occurrence of a character to the right. Cursor stops one character short. Repeat with <code>;</code>, reverse with <code>,</code>.",
    examples: [
      't, (move before next comma)',
      'dt; (delete till semicolon)',
      'ct) (change till close paren)',
    ],
    secondaryText: "'till",
  },
  T: {
    title: 'UPPERCASE',
    action: 'motion',
    hasDot: true,
    vimHelp: 'motion.txt.html#T',
    plugins:
      'dahu/vim-fanfingtastic | Extends f, F, t, T to search across multiple lines.',
    text: "Till backward — move cursor to just <b>after</b> the [count]'th occurrence of a character to the left.",
    examples: ['T(', 'dT, (delete back till comma)'],
    secondaryText: "back 'till",
  },
  u: {
    title: 'lowercase',
    action: 'command',
    vimHelp: 'undo.txt.html#u',
    text: 'Undo the last change. Repeat to undo further. Use <code>Ctrl-r</code> to redo.',
    examples: [
      'u (undo)',
      '3u (undo 3 changes)',
      'Ctrl-r (redo)',
      'U (undo all changes on line)',
    ],
    secondaryText: 'undo',
  },
  U: {
    title: 'UPPERCASE',
    action: 'command',
    vimHelp: 'undo.txt.html#U',
    text: 'Undo all changes made on the line of the last change. Note: this itself counts as a change and can be undone with <code>u</code>.',
    examples: ['U'],
    secondaryText: 'undo line',
  },
  v: {
    title: 'lowercase',
    action: 'command',
    vimHelp: 'visual.txt.html#v',
    text: 'Enter Visual mode (character-wise selection). Move to extend the selection, then apply an operator. <code>V</code> selects whole lines, <code>Ctrl-v</code> starts Visual Block mode for column selections.',
    examples: [
      'v (start select)',
      'vw (select to end of word)',
      'viw (select inner word)',
      'v$d (select to end, delete)',
      'Ctrl-v (visual block)',
      'Ctrl-v I# (comment column)',
    ],
    secondaryText: 'visual mode',
  },
  V: {
    title: 'UPPERCASE',
    action: 'command',
    vimHelp: 'visual.txt.html#V',
    text: 'Enter Visual Line mode — selects whole lines at a time.',
    examples: [
      'V (select line)',
      'Vj (select 2 lines)',
      'Vy (copy line)',
      'V>  (indent line)',
    ],
    secondaryText: 'visual lines',
    shortText: 'vis lns',
  },
  w: {
    title: 'lowercase',
    action: 'motion',
    vimHelp: 'motion.txt.html#w',
    plugins:
      'wesQ3/vim-windowswap | Swap window buffers with &lt;leader&gt;ww on each target. || bkad/CamelCaseMotion | Adds <leader>w / <leader>b / <leader>e to move by subword within CamelCase and snake_case identifiers.',
    text: 'Move forward [count] words. Stops at the <b>start</b> of each word. Punctuation counts as word boundaries.',
    examples: [
      'w',
      '3w',
      'dw (delete word)',
      'cw (change word)',
      'vw (select word)',
    ],
    secondaryText: 'next word',
  },
  W: {
    title: 'UPPERCASE',
    action: 'motion',
    vimHelp: 'motion.txt.html#W',
    text: 'Move forward [count] WORDS. Like <code>w</code> but only whitespace counts as a boundary — punctuation is skipped.',
    examples: ['W', '3W', 'dW', 'cW'],
    secondaryText: 'next WORD',
  },
  x: {
    title: 'lowercase',
    action: 'command',
    vimHelp: 'change.txt.html#x',
    plugins:
      'tpope/vim-speeddating | Increment dates, times, and more with CTRL-a/CTRL-x. || tommcdo/vim-exchange | cx{motion} marks a region to exchange. Use cx on another region to swap them. cxx for whole line. X in visual mode.',
    text: 'Delete [count] characters <b>under and after</b> the cursor. The deleted text goes into the unnamed register.',
    examples: [
      'x (delete char)',
      '3x (delete 3 chars)',
      'xp (transpose two chars)',
    ],
    secondaryText: 'delete char',
    numberIndicator: '2',
  },
  X: {
    title: 'UPPERCASE',
    action: 'command',
    vimHelp: 'change.txt.html#X',
    text: 'Delete [count] characters <b>before</b> the cursor. Like Backspace in normal mode.',
    examples: ['X', '3X'],
    secondaryText: 'back-space',
  },
  y: {
    title: 'lowercase',
    action: 'operator',
    vimHelp: 'change.txt.html#y',
    plugins:
      'tpope/vim-surround | ys{motion}{char} adds surrounding. e.g. ysiw" wraps word in quotes, yss( wraps whole line in parens, ysip} wraps paragraph in braces.',
    text: 'Yank (copy) the text covered by the motion into a register. Double <code>yy</code> yanks the whole line. Paste with <code>p</code> or <code>P</code>.',
    examples: [
      'yy or Y (yank line)',
      'yw (yank word)',
      'y$ (yank to end of line)',
      'yiw (yank inner word)',
      '"ay$ (yank to register a)',
    ],
    secondaryText: 'yank',
    numberIndicator: ['1', '3'],
  },
  Y: {
    title: 'UPPERCASE',
    action: 'command',
    vimHelp: 'change.txt.html#Y',
    text: 'Yank the current line (same as <code>yy</code>).',
    examples: ['Y', '"aY (yank line to register a)'],
    secondaryText: 'yank line',
  },
  z: {
    title: 'lowercase',
    action: 'extra',
    hasDot: true,
    vimHelp: 'index.txt.html#z',
    text: 'Prefix for scroll and fold commands. Toggle the <b>z</b> overlay in the header to see all <code>z+key</code> mappings.',
    examples: [
      'zz (center screen on cursor)',
      'zt (cursor to top)',
      'zb (cursor to bottom)',
      'za (toggle fold)',
      'zo / zc (open / close fold)',
    ],
    secondaryText: 'scroll/fold',
    shortText: 'scroll cmds',
    numberIndicator: '5',
  },
  Z: {
    title: 'UPPERCASE',
    action: 'extra',
    hasDot: true,
    vimHelp: 'starting.txt.html#-Z',
    text: '<code>ZZ</code> — save and quit (same as <code>:wq</code>). <code>ZQ</code> — quit without saving (same as <code>:q!</code>).',
    examples: ['ZZ (save & quit)', 'ZQ (quit without saving)'],
    secondaryText: 'quit',
    numberIndicator: '4',
  },
}
