import { KeyInfoType } from './types';

export const letters: Record<string, KeyInfoType> = {
  a: {
    title: 'lowercase',
    image: '/images/letters/a.png',
    action: 'command',
    hasBorder: true,
    vimhelp: 'insert.txt.html#a',
    plugins:
      'tpope/vim-speeddating | Use CTRL-a/CTRL-x to increment dates, times, and more.',
    text: 'insert after cursor<br>{command} around {selector}<br>ctrl-a: ++',
    secondaryText: 'append',
  },
  A: {
    title: 'UPPERCASE',
    image: '/images/letters/aa.png',
    action: 'command',
    hasBorder: true,
    vimhelp: 'insert.txt.html#A',
    text: 'append at end of line',
    secondaryText: 'append at col',
  },
  b: {
    title: 'lowercase',
    image: '/images/letters/b.png',
    action: 'motion',
    vimhelp: 'motion.txt.html#b',
    text: '[count] words backward.  |exclusive| motion.',
    secondaryText: 'prev word',
  },
  B: {
    title: 'UPPERCASE',
    image: '/images/letters/bb.png',
    action: 'motion',
    vimhelp: 'motion.txt.html#B',
    text: '[count] WORDS backward.  |exclusive| motion.',
    secondaryText: 'prev WORD',
  },
  c: {
    title: 'lowercase',
    image: '/images/letters/c.png',
    action: 'operator',
    vimhelp: 'change.txt.html#c',
    text: '["x]c{motion}<br>Delete {motion}text [into register x] and start insert.',
    secondaryText: 'change',
  },
  C: {
    title: 'UPPERCASE',
    image: '/images/letters/cc.png',
    action: 'command',
    hasBorder: true,
    vimhelp: 'change.txt.html#C',
    text: '["x]C<br>Delete from the cursor position to the end of the line and [count]-1 more lines [into register x], and start insert.<br>Synonym for c$ (not |linewise|).',
    secondaryText: 'change to end of line',
  },
  d: {
    title: 'lowercase',
    image: '/images/letters/d.png',
    action: 'operator',
    vimhelp: 'change.txt.html#d',
    text: '["x]d{motion}<br>Delete text that {motion} moves over [into register x].',
    secondaryText: 'delete',
  },
  D: {
    title: 'UPPERCASE',
    image: '/images/letters/dd.png',
    action: 'command',
    vimhelp: 'change.txt.html#D',
    text: '["x]D<br>Delete the characters under the cursor until the end of the line and [count]-1 more lines [into register x];<br>Synonym for "d$" .',
    secondaryText: 'delete to end of line',
  },
  e: {
    title: 'lowercase',
    image: '/images/letters/e.png',
    action: 'motion',
    vimhelp: 'motion.txt.html#e',
    text: 'Forward to the end of word [count] |inclusive|.  Does not stop in an empty line.',
    secondaryText: 'end word',
  },
  E: {
    title: 'UPPERCASE',
    image: '/images/letters/ee.png',
    action: 'motion',
    vimhelp: 'motion.txt.html#E',
    text: 'Forward to the end of WORD [count] |inclusive|.  Does not stop in an empty line.',
    secondaryText: 'end WORD',
  },
  f: {
    title: 'lowercase',
    image: '/images/letters/f.png',
    action: 'motion',
    hasDot: true,
    vimhelp: 'motion.txt.html#f',
    text: " f{char}<br>  To [count]'th occurrence of {char} to the right.<br>The cursor is placed on {char} |inclusive|.<br> {char} can be entered as a digraph.  When 'encoding' is set to Unicode, composing characters may be used.",
    secondaryText: 'find char',
  },
  F: {
    title: 'UPPERCASE',
    image: '/images/letters/ff.png',
    action: 'motion',
    hasDot: true,
    vimhelp: 'motion.txt.html#F',
    text: "F{char}<br>To the [count]'th occurrence of {char} to the left.<br> The cursor is placed on {char} |exclusive|.<br> {char} can be entered like with the |f| command.",
    secondaryText: '"back" find char',
  },
  g: {
    title: 'lowercase',
    image: '/images/letters/g.png',
    action: 'extra',
    hasDot: true,
    vimhelp: 'index.txt.html#g',
    text: 'A lot of Vim power found here! check out :help g',
    secondaryText: 'extra cmds',
  },
  G: {
    title: 'UPPERCASE',
    image: '/images/letters/gg.png',
    action: 'motion',
    hasDot: true,
    vimhelp: 'motion.txt.html#G',
    text: "Goto line [count], default last line, on the first non-blank character |linewise|.<br> If 'startofline' not set, keep the same column.<br> G is a one of |jump-motions|.",
    secondaryText: 'eof/goto line',
  },
  h: {
    title: 'lowercase',
    image: '/images/letters/h.png',
    action: 'motion',
    vimhelp: 'motion.txt.html#h',
    text: 'Move left',
    secondaryText: '←',
  },
  H: {
    title: 'UPPERCASE',
    image: '/images/letters/hh.png',
    action: 'motion',
    vimhelp: 'motion.txt.html#H',
    text: 'Move to top of current visable window.',
    secondaryText: 'screen top',
  },
  i: {
    title: 'lowercase',
    image: '/images/letters/i.png',
    action: 'command',
    hasBorder: true,
    vimhelp: 'insert.txt.html#i',
    text: 'Enter into insert mode from normal mode.',
    secondaryText: 'insert mode',
  },
  I: {
    title: 'UPPERCASE',
    image: '/images/letters/ii.png',
    action: 'command',
    hasBorder: true,
    vimhelp: 'insert.txt.html#I',
    text: 'Enter into insert mode at the beginning of the line.',
    secondaryText: 'insert mode at beginning of line',
  },
  j: {
    title: 'lowercase',
    image: '/images/letters/j.png',
    action: 'motion',
    vimhelp: 'motion.txt.html#j',
    text: 'Move down while in normal mode',
    secondaryText: '→',
  },
  J: {
    title: 'UPPERCASE',
    image: '/images/letters/jj.png',
    action: 'command',
    vimhelp: 'change.txt.html#J',
    text: 'Join next line to this line. Moves cursor to joined location',
    secondaryText: 'join lines',
  },
  k: {
    title: 'lowercase',
    image: '/images/letters/k.png',
    action: 'motion',
    vimhelp: 'motion.txt.html#k',
    text: 'Move up.',
    secondaryText: '↑',
  },
  K: {
    title: 'UPPERCASE',
    image: '/images/letters/kk.png',
    action: 'command',
    vimhelp: 'various.txt.html#K',
    text: 'Pulls up :man or :help on current word.',
    secondaryText: 'help',
  },
  l: {
    title: 'lowercase',
    image: '/images/letters/l.png',
    action: 'motion',
    vimhelp: 'motion.txt.html#l',
    text: 'Move right.',
    secondaryText: '↓',
  },
  L: {
    title: 'UPPERCASE',
    image: '/images/letters/ll.png',
    action: 'motion',
    vimhelp: 'motion.txt.html#L',
    text: 'Move to to near bottom of current visable window.',
    secondaryText: 'screen bottom',
  },
  m: {
    title: 'lowercase',
    image: '/images/letters/m.png',
    action: 'command',
    hasDot: true,
    vimhelp: 'motion.txt.html#m',
    text: "Set a Mark {a-zA-Z}. Use ' or ` to jump back to set mark {a-zA-Z}.",
    secondaryText: 'set mark',
  },
  M: {
    title: 'UPPERCASE',
    image: '/images/letters/mm.png',
    action: 'motion',
    vimhelp: 'motion.txt.html#M',
    text: 'Move to the middle of the current visable window.',
    secondaryText: 'screen middle',
  },
  n: {
    title: 'lowercase',
    image: '/images/letters/n.png',
    action: 'motion',
    vimhelp: 'pattern.txt.html#n',
    text: 'Move to next search item.',
    secondaryText: 'next(find)',
  },
  N: {
    title: 'UPPERCASE',
    image: '/images/letters/nn.png',
    action: 'motion',
    vimhelp: 'pattern.txt.html#N',
    text: 'Move to next search item in reverse.',
    secondaryText: 'prev(find)',
  },
  o: {
    title: 'lowercase',
    image: '/images/letters/o.png',
    action: 'command',
    hasBorder: true,
    vimhelp: 'insert.txt.html#o',
    text: 'Start a new line <b>below</b> cursor position.',
    secondaryText: 'open below',
  },
  O: {
    title: 'UPPERCASE',
    image: '/images/letters/oo.png',
    action: 'command',
    hasBorder: true,
    vimhelp: 'insert.txt.html#O',
    text: 'Start a new line <b>above</b> cursor position.',
    secondaryText: 'open above',
  },
  p: {
    title: 'lowercase',
    image: '/images/letters/p.png',
    action: 'command',
    vimhelp: 'change.txt.html#p',
    text: 'Paste after cursor.',
    secondaryText: 'paste after',
  },
  P: {
    title: 'UPPERCASE',
    image: '/images/letters/pp.png',
    action: 'command',
    vimhelp: 'change.txt.html#P',
    text: 'Paste before cursor.',
    secondaryText: 'paste before',
  },
  q: {
    title: 'lowercase',
    image: '/images/letters/q.png',
    action: 'command',
    hasDot: true,
    vimhelp: 'repeat.txt.html#q',
    text: 'Start recording a macro. Use {a-z} for a fresh start or {A-Z} for appending.',
    secondaryText: 'record',
  },
  Q: {
    title: 'UPPERCASE',
    image: '/images/letters/qq.png',
    action: 'command',
    vimhelp: 'intro.txt.html#Q',
    text: 'Enter into Ex mode where you can run commands like 21+21 and hit enter to get 42.',
    secondaryText: 'ex mode',
  },
  r: {
    title: 'lowercase',
    image: '/images/letters/r.png',
    action: 'command',
    hasDot: true,
    vimhelp: 'change.txt.html#r',
    text: 'Replace character under cursor with new character',
    secondaryText: 'replace char',
  },
  R: {
    title: 'UPPERCASE',
    image: '/images/letters/rr.png',
    action: 'command',
    hasBorder: true,
    vimhelp: 'change.txt.html#R',
    text: 'Replace each character as you type. Backspace will revert until you exit replace mode',
    secondaryText: 'replace mode',
  },
  s: {
    title: 'lowercase',
    image: '/images/letters/s.png',
    action: 'command',
    hasBorder: true,
    vimhelp: 'change.txt.html#s',
    text: 'Delete character(s) under cursor and enters insert mode.',
    secondaryText: 'substitute char',
  },
  S: {
    title: 'UPPERCASE',
    image: '/images/letters/ss.png',
    action: 'command',
    hasBorder: true,
    vimhelp: 'change.txt.html#S',
    text: 'Delete line(s) under cursor and enters insert mode.',
    secondaryText: 'substitute line',
  },
  t: {
    title: 'lowercase',
    image: '/images/letters/t.png',
    action: 'motion',
    vimhelp: 'motion.txt.html#t',
    text: "Move cursor to [count]'th occurance of character to the right.",
    secondaryText: "'till",
  },
  T: {
    title: 'UPPERCASE',
    image: '/images/letters/tt.png',
    action: 'motion',
    hasDot: true,
    vimhelp: 'motion.txt.html#T',
    text: "Move cursor to [count]'th occurance of character to the left.",
    secondaryText: "back 'till",
  },
  u: {
    title: 'lowercase',
    image: '/images/letters/u.png',
    action: 'command',
    vimhelp: 'undo.txt.html#u',
    text: 'Undo!',
    secondaryText: 'undo',
  },
  U: {
    title: 'UPPERCASE',
    image: '/images/letters/uu.png',
    action: 'command',
    vimhelp: 'undo.txt.html#U',
    text: 'Undo all changes on the line where the last change was made.',
    secondaryText: 'undo line',
  },
  v: {
    title: 'lowercase',
    image: '/images/letters/v.png',
    action: 'command',
    vimhelp: 'visual.txt.html#v',
    text: 'Enter Visual mode.',
    secondaryText: 'visual mode',
  },
  V: {
    title: 'UPPERCASE',
    image: '/images/letters/vv.png',
    action: 'command',
    vimhelp: 'visual.txt.html#V',
    text: 'Enter Visual mode linewise',
    secondaryText: 'visual lines',
  },
  w: {
    title: 'lowercase',
    image: '/images/letters/w.png',
    action: 'motion',
    vimhelp: 'motion.txt.html#w',
    plugins:
      'wesQ3/vim-windowswap | Buffer swapping `&lt;leader&gt;ww` on each buffer to swap positions',
    text: 'Move one word forward',
    secondaryText: 'next word',
  },
  W: {
    title: 'UPPERCASE',
    image: '/images/letters/ww.png',
    action: 'motion',
    vimhelp: 'motion.txt.html#W',
    text: 'Move one word backward',
    secondaryText: 'next WORD',
  },
  x: {
    title: 'lowercase',
    image: '/images/letters/x.png',
    action: 'command',
    vimhelp: 'change.txt.html#x',
    plugins:
      'tpope/vim-speeddating | Use CTRL-a/CTRL-x to increment dates, times, and more.',
    text: 'Delete character(s) under cursor and after.',
    secondaryText: 'delete char',
  },
  X: {
    title: 'UPPERCASE',
    image: '/images/letters/xx.png',
    action: 'command',
    vimhelp: 'change.txt.html#X',
    text: 'Delete character(s) under cursor and before.',
    secondaryText: 'backspace',
  },
  y: {
    title: 'lowercase',
    image: '/images/letters/y.png',
    action: 'operator',
    vimhelp: 'change.txt.html#y',
    text: 'Yank selected text',
    secondaryText: 'yank',
  },
  Y: {
    title: 'UPPERCASE',
    image: '/images/letters/yy.png',
    action: 'command',
    vimhelp: 'change.txt.html#Y',
    text: 'Yank current line.',
    secondaryText: 'yank line',
  },
  z: {
    title: 'lowercase',
    image: '/images/letters/z.png',
    action: 'extra',
    hasDot: true,
    vimhelp: 'index.txt.html#z',
    text: 'Redraw window on cursor. z+ for top of window z- for bottom of window and z. for center.',
    secondaryText: 'extra cmds',
  },
  Z: {
    title: 'UPPERCASE',
    image: '/images/letters/zz.png',
    action: 'extra',
    hasDot: true,
    vimhelp: 'starting.txt.html#-Z',
    text: 'Amazingly unmapped.',
    secondaryText: 'quit',
  },
};
