export type PrefixMode = 'none' | 'g' | 'z' | 'ctrl'

// Maps key character -> description for each prefix mode
export const gKeys: Record<string, string> = {
  g: 'go to first line (gg)',
  j: 'move down by display line',
  k: 'move up by display line',
  d: 'go to local definition',
  D: 'go to global definition',
  f: 'go to file under cursor',
  v: 'reselect last visual selection',
  q: 'format lines',
  u: 'lowercase {motion}',
  U: 'uppercase {motion}',
  '~': 'toggle case {motion}',
  '0': 'to start of display line',
  '^': 'to first non-blank of display line',
  '$': 'to end of display line',
  e: 'to end of previous word',
  E: 'to end of previous WORD',
  n: 'select next search match',
  ';': 'to older change list position',
  ',': 'to newer change list position',
  i: 'insert text before screen line',
  I: 'insert text before screen line (non-blank)',
  a: 'append text after screen line',
  A: 'append text after screen line (end)',
}

export const zKeys: Record<string, string> = {
  z: 'center cursor line (redraw)',
  t: 'cursor line to top of window',
  b: 'cursor line to bottom of window',
  '.': 'center cursor line (cursor to first non-blank)',
  o: 'open fold under cursor',
  O: 'open all folds under cursor',
  c: 'close fold under cursor',
  C: 'close all folds under cursor',
  a: 'toggle fold under cursor',
  A: 'toggle all folds under cursor',
  M: 'close all folds',
  R: 'open all folds',
  f: 'create fold for {motion}',
  d: 'delete fold at cursor',
  i: 'toggle foldenable',
  n: 'set foldenable off',
  N: 'set foldenable on',
  l: 'move cursor right, skip fold',
  h: 'move cursor left, skip fold',
  '+': 'same as zz (center)',
  '^': 'scroll to put cursor at top',
}

export const ctrlKeys: Record<string, string> = {
  d: 'scroll down half page',
  u: 'scroll up half page',
  f: 'scroll down full page',
  b: 'scroll up full page',
  e: 'scroll window down one line',
  y: 'scroll window up one line',
  r: 'redo',
  a: 'increment number under cursor',
  x: 'decrement number under cursor',
  o: 'jump back in jump list',
  i: 'jump forward in jump list',
  w: 'window command prefix',
  v: 'enter visual block mode',
  g: 'show file info',
  p: 'insert completion (previous)',
  n: 'insert completion (next)',
  '^': 'switch to alternate file',
  l: 'redraw screen',
  c: 'interrupt current command',
  '[': 'same as Escape',
  ']': 'tag jump',
  t: 'tag jump in new tab',
}

export const prefixKeyMaps: Record<string, Record<string, string>> = {
  g: gKeys,
  z: zKeys,
  ctrl: ctrlKeys,
}
