import type { KeyInfoType } from './types'

export const symbols: Record<string, KeyInfoType> = {
  '~': {
    title: 'Tilde',
    action: 'command',
    vimHelp: 'change.txt.html#%7e',
    text: '',
    secondaryText: 'toggle case',
  },
  '!': {
    title: 'Bang',
    action: 'operator',
    vimHelp: 'change.txt.html#%21',
    text: '',
    secondaryText: 'external filter',
  },
  '@': {
    title: 'At/Register',
    action: 'command',
    hasDot: true,
    vimHelp: 'repeat.txt.html#%40',
    text: ":let @q='_ctrl-r_ctrl-r_q (paste @q)<br>*modify*<br>' (closing quote) & _enter_<br><br>:g/pattern/d X (delete pattern and save to x register)",
    secondaryText: 'play macro',
  },
  '#': {
    title: 'Hash',
    action: 'motion',
    vimHelp: 'pattern.txt.html#%23',
    text: "Same as '*', but search backward.",
    secondaryText: 'prev ident',
  },
  $: {
    title: 'Money',
    action: 'motion',
    vimHelp: 'motion.txt.html#%24',
    text: 'To end of line',
    secondaryText: 'end of line',
  },
  '%': {
    title: 'Percent',
    action: 'motion',
    vimHelp: 'motion.txt.html#%25',
    text: 'Find the next item in this line after or under the cursor and jump to its match. |inclusive| motion.',
    secondaryText: 'goto match',
  },
  '^': {
    title: 'Caret',
    action: 'motion',
    vimHelp: 'motion.txt.html#%5e',
    text: 'Return to first non-blank character',
    secondaryText: "'soft' bol",
  },
  '&': {
    title: 'Ampersand',
    action: 'command',
    vimHelp: 'change.txt.html#%26',
    text: 'Synonym for `:s` (repeat last substitute)<br>Note that the flags are not remembered, thus it might actually work differently.<br>You can use `:&&` to keep the flags.',
    secondaryText: 'repeat :s',
  },
  '*': {
    title: 'Asterisk',
    action: 'motion',
    vimHelp: 'pattern.txt.html#star',
    text: "Search forward for the [count]'th occurrence of the word nearest to the cursor",
    secondaryText: 'next ident',
  },
  '(': {
    title: 'Begin parenthesis',
    action: 'motion',
    vimHelp: 'motion.txt.html#%28',
    text: '[count] sentences backward.  |exclusive| motion.',
    secondaryText: 'begin sentence',
  },
  ')': {
    title: 'End parenthesis',
    action: 'motion',
    vimHelp: 'motion.txt.html#%29',
    text: '[count] sentences forward.  |exclusive| motion.',
    secondaryText: 'end sentence',
  },
  _: {
    title: 'Underscore',
    action: 'motion',
    vimHelp: 'motion.txt.html#_',
    text: '[count] - 1 lines downward, on the first non-blank character |linewise|.',
    secondaryText: "'soft' bol down",
  },
  '+': {
    title: 'Plus',
    action: 'motion',
    vimHelp: 'motion.txt.html#%2b',
    text: '[count] lines downward, on the first non-blank character |linewise|.',
    secondaryText: 'next line',
  },
  '-': {
    title: 'Minus/Dash',
    action: 'motion',
    vimHelp: 'motion.txt.html#-',
    plugins: 'AndrewRadev/switch.vim | Change true/false, etc',
    text: '[count] lines upward, on the first non-blank character |linewise|.',
    secondaryText: 'prev line',
  },
  '=': {
    title: 'Equal',
    action: 'operator',
    vimHelp: 'change.txt.html#%3d',
    text: "Filter {motion} lines through the external program given with the 'equalprg' option.  When the 'equalprg' option is empty (this is the default), use the internal formatting function",
    secondaryText: 'auto format',
  },
  '`': {
    title: 'backtick',
    action: 'motion',
    hasDot: true,
    vimHelp: 'motion.txt.html#%60',
    text: 'Jump to the mark {a-z} in the current buffer.',
    secondaryText: 'goto mark',
  },
  '[': {
    title: 'Beginning Bracket',
    action: 'motion',
    hasDot: true,
    vimHelp: 'index.txt.html#%5b',
    plugins: 'tpope/vim-unimpaired | Adds many [x / ]x pairs: [b/]b buffers, [q/]q quickfix, [l/]l location list, [<Space>/]<Space> add blank lines, [e/]e exchange line, [p/]p paste above with indent.',
    text: 'Prefix for backward navigation commands. <code>[[</code> previous section, <code>[(</code> previous unmatched paren, <code>[{</code> previous unmatched brace, <code>[m</code> previous method start.',
    examples: ['[[', '[(', '[{', '[m (prev method)'],
    secondaryText: 'prev section',
  },
  ']': {
    title: 'Ending Bracket',
    action: 'motion',
    hasDot: true,
    vimHelp: 'index.txt.html#%5d',
    plugins: 'tpope/vim-unimpaired | Adds many [x / ]x pairs: [b/]b buffers, [q/]q quickfix, [l/]l location list, [<Space>/]<Space> add blank lines, [e/]e exchange line.',
    text: 'Prefix for forward navigation commands. <code>]]</code> next section, <code>])</code> next unmatched paren, <code>]}</code> next unmatched brace, <code>]m</code> next method start.',
    examples: [']]', '])', ']}', ']m (next method)'],
    secondaryText: 'next section',
  },
  '{': {
    title: 'Begin Brace',
    action: 'motion',
    vimHelp: 'motion.txt.html#%7b',
    text: '[count] paragraphs backward.  |exclusive| motion.',
    secondaryText: 'begin paragraph',
  },
  '}': {
    title: 'End Brace',
    action: 'motion',
    vimHelp: 'motion.txt.html#%7d',
    text: '[count] paragraphs forward.  |exclusive| motion.',
    secondaryText: 'end paragraph',
  },
  '?': {
    title: 'Question Mark',
    action: 'motion',
    hasDot: true,
    vimHelp: 'pattern.txt.html#%3f',
    text: "Search backward for the [count]'th occurrence of the latest used pattern |last-pattern| with latest used |{offset}|.",
    secondaryText: 'find (reverse)',
  },
  '/': {
    title: 'Forward Slash',
    action: 'motion',
    hasDot: true,
    vimHelp: 'pattern.txt.html#%2f',
    text: "Search forward for the [count]'th occurrence of the latest used pattern |last-pattern| with latest used |{offset}|.",
    secondaryText: 'find',
  },
  '\\': {
    title: 'Back Slash',
    action: 'extra',
    hasDot: true,
    vimHelp: 'pattern.txt.html#%2f%5c',
    text: 'A backslash followed by a single character, with no special meaning, is reserved for future expansions',
    secondaryText: 'not used!',
  },
  '|': {
    title: 'Pipe',
    action: 'motion',
    vimHelp: 'motion.txt.html#bar',
    text: '',
    secondaryText: 'bol/goto col',
  },
  '.': {
    title: 'dot',
    action: 'command',
    vimHelp: 'repeat.txt.html#.',
    plugins: 'tpope/vim-repeat | Makes . repeat work correctly with plugin commands (vim-surround, vim-commentary, etc.) instead of only built-in changes.',
    text: 'Repeat the last change. One of the most powerful keys in Vim — combine with motions to apply changes repeatedly.',
    examples: ['cwiNEW<Esc> then . (change next word)', 'dd then . (delete next line)', 'A;<Esc> then j. (add ; to multiple lines)'],
    secondaryText: 'repeat last',
  },
  ',': {
    title: 'Comma',
    action: 'motion',
    vimHelp: 'motion.txt.html#%2c',
    text: '',
    secondaryText: 'reverse f/F/t/T',
  },
  '"': {
    title: 'Double Quote',
    action: 'extra',
    hasDot: true,
    vimHelp: 'pattern.txt.html#%2f%5c',
    text: '',
    secondaryText: 'reg spec',
  },
  "'": {
    title: 'Single Quote',
    action: 'motion',
    hasDot: true,
    vimHelp: 'motion.txt.html#%27',
    text: "'< & '> start/end of visual selection<br> '[ & '] - start/end of last change or yank<br> '. - position of where last change was made<br> '^ - position of cursor when last Vim last left insert mode - This is how gi command works<br> '' - position before last jump (Super useful!). See :h ''<br>` (backtick) Go to line AND column",
    secondaryText: 'goto mark bol',
  },
  ';': {
    title: 'Semicolon',
    action: 'motion',
    vimHelp: 'motion.txt.html#%3b',
    text: '',
    secondaryText: 'repeat f/F/t/T',
  },
  ':': {
    title: 'Colon',
    action: 'command',
    vimHelp: 'cmdline.txt.html#%3a',
    text: 'Execute a command',
    secondaryText: 'ex command line',
  },
  '>': {
    title: 'Greater than',
    action: 'operator',
    vimHelp: 'change.txt.html#%3e',
    text: '',
    secondaryText: 'indent',
    numberIndicator: '3',
  },
  '<': {
    title: 'Less than',
    action: 'operator',
    vimHelp: 'change.txt.html#%3c',
    text: '',
    secondaryText: 'un-indent',
    numberIndicator: '3',
  },
}
