import type { KeyInfoType } from './types'

export const symbols: Record<string, KeyInfoType> = {
  '~': {
    title: 'Tilde',
    action: 'command',
    vimHelp: 'change.txt.html#%7e',
    text: 'Toggle the case of the character under cursor and advance. Use <code>g~{motion}</code> to toggle case over a range, <code>g~~</code> for the whole line, <code>gU</code> to uppercase, <code>gu</code> to lowercase.',
    examples: [
      '~',
      '5~',
      'g~~',
      'g~iw (toggle inner word)',
      'gUiw (uppercase word)',
      'guiw (lowercase word)',
    ],
    secondaryText: 'toggle case',
  },
  '!': {
    title: 'Bang',
    action: 'operator',
    vimHelp: 'change.txt.html#%21',
    text: "Filter {motion} lines through an external shell command. The selected lines are replaced with the command's output. <code>!!</code> filters the current line.",
    examples: [
      '!ip sort (sort paragraph)',
      '!} sort -r (sort next block reversed)',
      ':.!date (insert date on current line)',
      '!G sort -u (sort + dedupe to EOF)',
    ],
    secondaryText: 'external filter',
  },
  '@': {
    title: 'At/Register',
    action: 'command',
    hasDot: true,
    vimHelp: 'repeat.txt.html#%40',
    text: "Execute the macro stored in register <code>{a-z}</code>. Use <code>@@</code> to repeat the last macro. To edit a macro: <code>:let @q='</code> then <code>Ctrl-r Ctrl-r q</code> to paste it, edit, close quote and press Enter.",
    examples: [
      '@q (run macro q)',
      '@@  (repeat last macro)',
      '5@q (run 5 times)',
      ":let @q='...' (edit macro)",
    ],
    secondaryText: 'play macro',
  },
  '#': {
    title: 'Hash',
    action: 'motion',
    vimHelp: 'pattern.txt.html#%23',
    text: 'Search <b>backward</b> for the word under the cursor. Like <code>*</code> but in reverse. Use <code>n</code>/<code>N</code> to continue navigating matches.',
    examples: [
      '# (search back for word)',
      '3# (3rd prev match)',
      'g# (partial word match backward)',
    ],
    secondaryText: 'prev ident',
  },
  $: {
    title: 'Dollar',
    action: 'motion',
    vimHelp: 'motion.txt.html#%24',
    text: 'Move to the end of the line. With a count, moves to the end of [count]-1 lines down.',
    examples: [
      '$ (end of line)',
      'd$ or D (delete to end)',
      'y$ (yank to end)',
      'c$ or C (change to end)',
      '2$ (end of next line)',
    ],
    secondaryText: 'end of line',
  },
  '%': {
    title: 'Percent',
    action: 'motion',
    vimHelp: 'motion.txt.html#%25',
    plugins:
      'andymass/vim-matchup | Extends % to match if/else/end, HTML/XML tags, and language-specific block pairs. Drop-in replacement for the built-in matchit.',
    text: 'Jump to the matching bracket, paren, or brace under/after the cursor. With a count (e.g. <code>50%</code>), jump to that percentage of the file. Enable <code>matchit</code> (built-in, not loaded by default) with <code>:packadd matchit</code> for HTML/XML tag and if/end matching.',
    examples: [
      '% (jump to match)',
      'd% (delete to match)',
      'v% (select to match)',
      '50% (go to middle of file)',
      ':packadd matchit (enable tag matching)',
    ],
    secondaryText: 'goto match',
  },
  '^': {
    title: 'Caret',
    action: 'motion',
    vimHelp: 'motion.txt.html#%5e',
    text: 'Move to the first <b>non-blank</b> character of the line. Unlike <code>0</code> which always goes to column 1.',
    examples: [
      '^',
      'd^ (delete to first non-blank)',
      'c^',
      'I (insert at ^ position)',
    ],
    secondaryText: 'first non-blank',
  },
  '&': {
    title: 'Ampersand',
    action: 'command',
    vimHelp: 'change.txt.html#%26',
    text: 'Repeat the last <code>:s</code> substitute command on the current line, but <b>without</b> the flags. Use <code>:&&</code> to repeat with flags, or <code>g&</code> to repeat on all lines.',
    examples: [
      '& (repeat last :s)',
      ':&& (repeat with flags)',
      'g& (repeat on all lines)',
    ],
    secondaryText: 'repeat :s',
  },
  '*': {
    title: 'Asterisk',
    action: 'motion',
    vimHelp: 'pattern.txt.html#star',
    plugins:
      'haya14busa/vim-asterisk | Extends * so the cursor stays on the current match instead of jumping to the next one. Supports z* (no-jump) and visual star.',
    text: 'Search <b>forward</b> for the word under the cursor (whole word match). Use <code>g*</code> for a partial match. Sets the search register — use <code>n</code>/<code>N</code> to navigate.',
    examples: [
      '* (search forward for word)',
      'g* (partial word match)',
      'ciw then n. (change word, repeat)',
      '# (search backward for word)',
    ],
    secondaryText: 'next ident',
  },
  '(': {
    title: 'Begin parenthesis',
    action: 'motion',
    vimHelp: 'motion.txt.html#%28',
    text: 'Move backward [count] sentences. A sentence ends at <code>.</code>, <code>!</code>, or <code>?</code> followed by whitespace or end of line.',
    examples: [
      '(',
      '3(',
      'd( (delete to sentence start)',
      'v( (select to sentence start)',
    ],
    secondaryText: 'prev sentence',
  },
  ')': {
    title: 'End parenthesis',
    action: 'motion',
    vimHelp: 'motion.txt.html#%29',
    text: 'Move forward [count] sentences.',
    examples: [')', '3)', 'd)', 'y) (yank sentence)'],
    secondaryText: 'next sentence',
  },
  _: {
    title: 'Underscore',
    action: 'motion',
    vimHelp: 'motion.txt.html#_',
    text: 'Move to the first non-blank character of [count]-1 lines down. With no count, stays on the current line (like <code>^</code>).',
    examples: [
      '_ (first non-blank, same line)',
      '2_ (next line first non-blank)',
      'd_ (delete to first non-blank)',
    ],
    secondaryText: 'soft bol down',
  },
  '+': {
    title: 'Plus',
    action: 'motion',
    vimHelp: 'motion.txt.html#%2b',
    text: 'Move to the first non-blank character of the next [count] lines. Same as pressing <code>Enter</code> in Normal mode.',
    examples: ['+', '3+', 'd+ (delete current + next line)'],
    secondaryText: 'next line bol',
  },
  '-': {
    title: 'Minus',
    action: 'motion',
    vimHelp: 'motion.txt.html#-',
    plugins:
      'andrewRadev/switch.vim | Press - to toggle values under cursor: true↔false, yes↔no, &&↔||, and more. Configurable per filetype.',
    text: 'Move to the first non-blank character of the previous [count] lines.',
    examples: ['-', '3-', 'd-'],
    secondaryText: 'prev line bol',
  },
  '=': {
    title: 'Equal',
    action: 'operator',
    vimHelp: 'change.txt.html#%3d',
    text: "Auto-indent operator — re-indents the text covered by the motion using Vim's built-in formatter (or <code>equalprg</code> if set). <code>==</code> formats the current line. Set <code>equalprg</code> to pipe through an external formatter: <code>set equalprg=prettier\\ --stdin-filepath\\ %</code>.",
    examples: [
      '== (format line)',
      '=G (format to end of file)',
      '=ip (format paragraph)',
      'gg=G (format whole file)',
      '=% (format to matching bracket)',
      ':set equalprg=black\\ - (use black for Python)',
    ],
    secondaryText: 'auto indent',
  },
  '`': {
    title: 'Backtick',
    action: 'motion',
    hasDot: true,
    vimHelp: 'motion.txt.html#%60',
    text: "Jump to the <b>exact position</b> (line and column) of a mark. Unlike <code>'</code> which jumps to the line start. Special marks: <code>``</code> before last jump, <code>`.</code> last change, <code>`[</code>/<code>`]</code> start/end of last yank.",
    examples: [
      '`a (exact pos of mark a)',
      '`` (jump back)',
      '`. (last change position)',
      '`[ (start of last yank)',
      'd`a (delete to mark a)',
    ],
    secondaryText: 'goto mark (exact)',
  },
  '[': {
    title: 'Opening Bracket',
    action: 'motion',
    hasDot: true,
    vimHelp: 'index.txt.html#%5b',
    plugins:
      'tpope/vim-unimpaired | [b/]b prev/next buffer, [q/]q quickfix, [l/]l location list, [<Space>/]<Space> add blank line, [e/]e exchange line up/down, [p/]p paste above with indent.',
    text: 'Prefix for backward navigation. <code>[[</code> prev section, <code>[(</code> prev unmatched <code>(</code>, <code>[{</code> prev unmatched <code>{</code>, <code>[m</code> prev method start, <code>[/</code> prev comment start.',
    examples: ['[[', '[(', '[{', '[m (prev method)', '[/ (prev comment)'],
    secondaryText: 'prev section',
  },
  ']': {
    title: 'Closing Bracket',
    action: 'motion',
    hasDot: true,
    vimHelp: 'index.txt.html#%5d',
    plugins:
      'tpope/vim-unimpaired | [b/]b prev/next buffer, [q/]q quickfix, [l/]l location list, [<Space>/]<Space> add blank line, [e/]e exchange line up/down.',
    text: 'Prefix for forward navigation. <code>]]</code> next section, <code>])</code> next unmatched <code>)</code>, <code>]}</code> next unmatched <code>}</code>, <code>]m</code> next method start, <code>]/</code> next comment end.',
    examples: [']]', '])', ']}', ']m (next method)', ']/ (next comment end)'],
    secondaryText: 'next section',
  },
  '{': {
    title: 'Opening Brace',
    action: 'motion',
    vimHelp: 'motion.txt.html#%7b',
    text: 'Move backward [count] paragraphs. A paragraph boundary is a blank line or a section boundary.',
    examples: [
      '{',
      '3{',
      'd{ (delete to paragraph start)',
      'v{ (select back)',
      'y{ (yank back)',
    ],
    secondaryText: 'prev paragraph',
  },
  '}': {
    title: 'Closing Brace',
    action: 'motion',
    vimHelp: 'motion.txt.html#%7d',
    text: 'Move forward [count] paragraphs.',
    examples: [
      '}',
      '3}',
      'd} (delete paragraph)',
      'y} (yank paragraph)',
      'v} (select paragraph)',
    ],
    secondaryText: 'next paragraph',
  },
  '?': {
    title: 'Question Mark',
    action: 'motion',
    hasDot: true,
    vimHelp: 'pattern.txt.html#%3f',
    text: 'Search <b>backward</b> — opens a search prompt. Like <code>/</code> but in reverse. Accepts the same regex syntax. <code>n</code> continues backward, <code>N</code> goes forward.',
    examples: [
      '?pattern',
      '?\\<word\\> (exact word back)',
      '? (repeat last search backward)',
    ],
    secondaryText: 'search backward',
  },
  '/': {
    title: 'Forward Slash',
    action: 'motion',
    hasDot: true,
    vimHelp: 'pattern.txt.html#%2f',
    text: 'Search <b>forward</b> — opens a search prompt. Supports regex. After searching, <code>n</code> jumps to next match, <code>N</code> previous. Use <code>:noh</code> to clear highlights.',
    examples: [
      '/pattern',
      '/\\<word\\> (exact word)',
      '/pattern/e (land at end of match)',
      ':noh (clear highlights)',
      'cgn (change next match)',
    ],
    secondaryText: 'search forward',
  },
  '\\': {
    title: 'Backslash',
    action: 'extra',
    hasDot: true,
    vimHelp: 'pattern.txt.html#%2f%5c',
    text: 'Not a standalone command — used as the default <code>mapleader</code> and as an escape character in regex patterns (<code>\\n</code> newline, <code>\\t</code> tab, <code>\\<</code>/<code>\\></code> word boundaries, <code>\\v</code> very magic mode).',
    examples: [
      '\\n (newline in regex)',
      '\\<word\\> (word boundary)',
      '\\v (very magic mode)',
      ':let mapleader=","',
    ],
    secondaryText: 'leader / regex',
  },
  '|': {
    title: 'Pipe',
    action: 'motion',
    vimHelp: 'motion.txt.html#bar',
    text: 'Move to column [count]. Without a count, moves to column 1 (same as <code>0</code>).',
    examples: ['| (column 1)', '5| (column 5)', '80| (column 80)'],
    secondaryText: 'goto column',
  },
  '.': {
    title: 'Dot',
    action: 'command',
    vimHelp: 'repeat.txt.html#.',
    plugins:
      'tpope/vim-repeat | Makes . work correctly with plugin commands (vim-surround, vim-commentary, etc.) instead of only built-in changes.',
    text: 'Repeat the last change. One of the most powerful keys in Vim — combine with motions and <code>n</code> to apply changes across a file efficiently.',
    examples: [
      'cwiNEW<Esc> then . (change next word)',
      'dd then . (delete next line)',
      'A;<Esc> then j. (add ; to each line)',
      'n. (repeat change on next match)',
    ],
    secondaryText: 'repeat last',
  },
  ',': {
    title: 'Comma',
    action: 'motion',
    vimHelp: 'motion.txt.html#%2c',
    text: 'Repeat the last <code>f</code>, <code>F</code>, <code>t</code>, or <code>T</code> search in the <b>opposite</b> direction.',
    examples: [', (after f( → find prev "(")', '3, (3rd previous match)'],
    secondaryText: 'reverse f/t',
  },
  '"': {
    title: 'Double Quote',
    action: 'extra',
    hasDot: true,
    vimHelp: 'change.txt.html#registers',
    text: 'Specify a <b>register</b> for the next delete, yank, or paste. Special registers: <code>"0</code> last yank, <code>"_</code> black hole, <code>"+</code> system clipboard, <code>"%</code> current filename, <code>":</code> last command.',
    examples: [
      '"ayy (yank line to register a)',
      '"ap (paste from register a)',
      '"_dd (delete to black hole)',
      '"+p (paste from clipboard)',
      '"0p (paste last yank, ignoring deletes)',
    ],
    secondaryText: 'register',
  },
  "'": {
    title: 'Single Quote',
    action: 'motion',
    hasDot: true,
    vimHelp: 'motion.txt.html#%27',
    text: "Jump to the <b>first non-blank</b> of the line containing a mark. Special marks: <code>''</code> before last jump, <code>'.</code> last change, <code>'^</code> last insert exit, <code>'<</code>/<code>'>  </code> visual selection start/end, <code>'[</code>/<code>']</code> last yank/change.",
    examples: [
      "'a (line of mark a)",
      "'' (jump back)",
      "'. (last change line)",
      "'< (start of last visual)",
      "d'a (delete to mark a)",
    ],
    secondaryText: 'goto mark bol',
  },
  ';': {
    title: 'Semicolon',
    action: 'motion',
    vimHelp: 'motion.txt.html#%3b',
    text: 'Repeat the last <code>f</code>, <code>F</code>, <code>t</code>, or <code>T</code> search in the <b>same</b> direction. Use <code>,</code> to go in reverse.',
    examples: [
      '; (after f( → find next "(")',
      '3; (3rd next match)',
      'f( then ; ; ; (navigate all parens)',
    ],
    secondaryText: 'repeat f/t',
  },
  ':': {
    title: 'Colon',
    action: 'command',
    vimHelp: 'cmdline.txt.html#%3a',
    text: 'Enter the command-line (Ex) mode. Type a command and press Enter to execute. Essential commands: <code>:w</code> save, <code>:q</code> quit, <code>:s</code> substitute, <code>:g</code> global, <code>:!</code> shell.',
    examples: [
      ':w (save)',
      ':q! (quit without saving)',
      ':%s/old/new/g (replace all)',
      ':g/pattern/d (delete matching lines)',
      ':help topic',
      ':set number',
    ],
    secondaryText: 'command line',
  },
  '>': {
    title: 'Greater Than',
    action: 'operator',
    vimHelp: 'change.txt.html#%3e',
    text: 'Indent operator — shifts the text covered by the motion right by one <code>shiftwidth</code>. Double <code>>></code> indents the current line.',
    examples: [
      '>> (indent line)',
      '3>> (indent 3 lines)',
      '>ip (indent paragraph)',
      '>% (indent to matching bracket)',
      'V3j> (select + indent)',
    ],
    secondaryText: 'indent',
    numberIndicator: '3',
  },
  '<': {
    title: 'Less Than',
    action: 'operator',
    vimHelp: 'change.txt.html#%3c',
    text: 'Unindent operator — shifts the text covered by the motion left by one <code>shiftwidth</code>. Double <code><<</code> unindents the current line.',
    examples: [
      '<< (unindent line)',
      '3<< (unindent 3 lines)',
      '<ip (unindent paragraph)',
      '<% (unindent to matching bracket)',
    ],
    secondaryText: 'un-indent',
    numberIndicator: '3',
  },
}
